default:
  image: node:fermium-alpine
  cache:
    key:
      files:
        - .nvmrc
        - package-lock.json
    paths:
      - node_modules/
  before_script:
    - npm ci

test:
  stage: test
  script:
    - npm run lint
    - npm run test
  coverage: '/^Statements\s*:\s*([^%]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

deploy:
  stage: deploy
  script:
    - npm run deploy:prod
  resource_group: production
  only:
    - main
