image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

before_script:
  - npm ci

test:
  stage: test
  script:
    - npm run test

deploy:
  stage: deploy
  script:
    - npm run deploy:prod
  only:
    - main
