default:
  image: node:fermium-alpine
  cache:
    paths:
      - node_modules/
  before_script:
    - npm ci

test:
  stage: test
  script:
    - npm run lint
    - npm run test

deploy:
  stage: deploy
  script:
    - npm run deploy:prod
  only:
    - main
