default:
  image: registry.gitlab.com/newcubator/newcubator/micro-bots/buildutil-node:20.18.3-alpine
  cache:
    key:
      files:
        - .nvmrc
        - package-lock.json
    paths:
      - node_modules/
  before_script:
    - grep -q $(node -v | cut -c2-) .nvmrc
    - >
      [[ -d node_modules ]] || npm ci

test:
  stage: test
  script:
    - npm run lint
    - npm run test
  coverage: '/^Statements\s*:\s*([^%]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

deploy:
  stage: deploy
  environment:
    name: production
    deployment_tier: production
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  script:
    - >
      export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
      $(aws sts assume-role-with-web-identity
      --role-arn arn:aws:iam::931595285256:role/GitlabCi
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token $GITLAB_OIDC_TOKEN
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text))
    - aws sts get-caller-identity
    - npm run deploy:prod
  only:
    - main
