service: micro-bots

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: production
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'ses:SendEmail'
          Resource: 'arn:aws:ses:eu-central-1:931595285256:identity/newcubator.com'
  environment:
    AWS_ACCESS_KEY_ID_GOOGLE: ${env:AWS_ACCESS_KEY_ID_GOOGLE}
    AWS_SECRET_ACCESS_KEY_GOOGLE: ${env:AWS_SECRET_ACCESS_KEY_GOOGLE}
    AWS_SECRET_NAME: ${env:AWS_SECRET_NAME}
    COMPLETION_NOTICE_CHANNEL: ${env:COMPLETION_NOTICE_CHANNEL}
    EMPLOYEE_NAMES: ${env:EMPLOYEE_NAMES}
    MOCO_TOKEN: ${env:MOCO_TOKEN}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SPREADSHEET_ID: ${env:AWS_SECRET_NAME}
    WORKLOAD_CHANNEL: ${env:WORKLOAD_CHANNEL}
    WORKLOAD_PERCENTAGE: ${env:WORKLOAD_PERCENTAGE}

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true

functions:
  birthday:
    handler: src/functions/birthday.handler
    memorySize: 128
    timeout: 10
    environment:
      LEAD_TIME: 21
    events:
      - schedule:
          rate: cron(5 4 * * ? *)
          enabled: true
  completionNotice:
    handler: src/functions/completion-notice.handler
    memorySize: 128
    timeout: 15
    events:
      - http:
          path: completionNotice
          method: post
  lockProject:
    handler: src/functions/lock-project.handler
    memorySize: 128
    events:
      - http:
          path: lockProject
          method: post
  mailSignature:
    handler: src/functions/mail-signature.handler
    memorySize: 128
    events:
      - http:
          path: mailSignature
          method: post
  eventApplication:
    handler: src/functions/event-application.handler
    memorySize: 128
    events:
      - http:
          path: eventApplication
          method: post
          cors: true
  unlockProject:
    handler: src/functions/unlock-project.handler
    memorySize: 128
    events:
      - http:
          path: unlockProject
          method: post
  workload:
    handler: src/functions/workload.handler
    memorySize: 128
    events:
      - http:
          path: workload
          method: post
  workloadAll:
    handler: src/functions/workload-all.handler
    memorySize: 128
    events:
      - http:
          path: workloadAll
          method: post
      - schedule:
          rate: cron(0 16 ? * FRI *)
          enabled: true
  coronaHannover:
    handler: src/functions/corona-hannover.handler
    memorySize: 128
    timeout: 10
    events:
      - schedule:
          rate: cron(* 8-20 * * *) # At every minute past hour 8 and 20.
          enabled: true
