service: birthday-bot

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: production
  environment:
    MOCO_TOKEN: ${env:MOCO_TOKEN}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    WORKLOAD_CHANNEL: ${env:WORKLOAD_CHANNEL}
    EMPLOYEE_NAMES: ${env:EMPLOYEE_NAMES}

plugins:
  - serverless-webpack

custom:
  webpack:
    includeModules: true

functions:
  birthday:
    handler: src/functions/birthday.handler
    memorySize: 128
    environment:
      LEAD_TIME: 21
    events:
      - schedule:
          rate: cron(5 8 * * ? *)
          enabled: true
  workload:
    handler: src/functions/workload.handler
    memorySize: 128
    events:
      - http:
          path: workload
          method: post
  workloadAll:
    handler: src/functions/workload-all.handler
    memorySize: 128
    events:
      - http:
          path: workloadAll
          method: post
      - schedule:
          rate: cron(0 16 ? * FRI *)
          enabled: true
