service: micro-bots

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  stage: production
  stackTags:
    Project: micro-bots
    GitlabProjectId: "20934853"
    GitlabProjectUrl: https://gitlab.com/newcubator/newcubator/micro-bots
    Environment: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: "arn:aws:ses:eu-central-1:931595285256:identity/newcubator.com"
        - Effect: "Allow"
          Action:
            - "events:PutEvents"
          Resource:
            - "*"
  # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  lambdaHashingVersion: 20201221
  eventBridge:
    # https://www.serverless.com/framework/docs/deprecations/#AWS_EVENT_BRIDGE_CUSTOM_RESOURCE
    useCloudFormation: true
  environment:
    NODE_OPTIONS: --enable-source-maps
    AWS_ACCESS_KEY_ID_GOOGLE: ${env:AWS_ACCESS_KEY_ID_GOOGLE}
    AWS_SECRET_ACCESS_KEY_GOOGLE: ${env:AWS_SECRET_ACCESS_KEY_GOOGLE}
    GITLAB_BOOK_PROJECT_ID: ${env:GITLAB_BOOK_PROJECT_ID}
    GITLAB_TOKEN: ${env:GITLAB_TOKEN}
    JIRA_PASSWORD_KWS: ${env:JIRA_PASSWORD_KWS}
    JIRA_USER_KWS: ${env:JIRA_USER_KWS}
    MOCO_TOKEN: ${env:MOCO_TOKEN}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    GENERAL_CHANNEL: ${env:GENERAL_CHANNEL}

plugins:
  - serverless-esbuild
  - serverless-sentry
  - serverless-prune-plugin

custom:
  esbuild:
    bundle: true
    sourcemap: true
  sentry:
    dsn: ${env:SENTRY_DSN}
  prune:
    automatic: true
    number: 5

functions:
  birthday:
    environment:
      LEAD_TIME: 21
    events:
      - schedule:
          enabled: true
          rate: cron(5 4 * * ? *) # at 4:05 AM (UTC) every day
    handler: src/functions/birthday.handler
    memorySize: 128
    timeout: 10
  bookIssueReminder:
    environment:
      GITLAB_PROJECT_ID: ${env:GITLAB_BOOK_PROJECT_ID}
      SLACK_CHANNEL_ID: ${env:GENERAL_CHANNEL}
    events:
      - schedule:
          enabled: true
          rate: cron(5 4 * * ? *) # at 4:05 AM (UTC) every day
    handler: src/functions/gitlab-issue-reminder.handler
    memorySize: 128
    timeout: 20

  aiBookDemoCommand:
    handler: src/ai-book-demo/ai-book-demo-command.commandHandler
    timeout: 3
    url: true

  aiBookDemoEvent:
    environment:
      BOOK_SUPPORT_SPREADSHEET_ID: ${env:BOOK_SUPPORT_SPREADSHEET_ID}
      OPENAI_TOKEN: ${env:OPENAI_TOKEN}
      GOOGLE_CLIENT_EMAIL: ${env:GOOGLE_CLIENT_EMAIL}
      GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "AiBookDemoRequestedEvent"
    handler: src/ai-book-demo/ai-book-demo-event.handler
    timeout: 20
    maximumRetryAttempts: 0
    memorySize: 512

  ##
  ## Completion Notice
  ##

  completionNoticeCommand:
    handler: src/completion-notice/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: completion-notice-command

  completionNoticeEvent:
    handler: src/completion-notice/event-handler.eventHandler
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "CompletionNoticeRequestedEvent"

  contactRequest:
    events:
      - http:
          cors: true
          method: post
          path: contactRequest
    handler: src/functions/contact-request.handler
    memorySize: 128
  eventApplication:
    events:
      - http:
          cors: true
          method: post
          path: eventApplication
    handler: src/functions/event-application.handler
    memorySize: 128

  kwsReport:
    handler: src/kws-report/command-handler.commandHandler
    timeout: 25
    events:
      - http:
          method: post
          path: kws-report

  kwsReportEvent:
    handler: src/kws-report/event-handler.eventHandler
    timeout: 25
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "KWSExcelExportRequestedEvent"

  ##
  ## Lock Project
  ##

  lockProjectCommand:
    handler: src/lock-project/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: lock-project-command

  lockProjectEvent:
    handler: src/lock-project/event-handler.eventHandler
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "LockProjectRequestedEvent"

  mailSignature:
    events:
      - http:
          method: post
          path: mailSignature
    handler: src/functions/mail-signature.handler
    memorySize: 128
  mailSignatureGenerator:
    events:
      - http:
          method: get
          path: mailSignatureGenerator
    handler: src/functions/mail-signature-generator.handler
    memorySize: 128

  privateChannelCommand:
    handler: src/private-channel/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: private-channel-command
  privateChannelEvent:
    handler: src/private-channel/event-handler.eventHandler
    timeout: 20
    maximumRetryAttempts: 0
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "PrivateChannelRequestedEvent"

  selectMenuHandler:
    handler: src/slack/select-menu-handler.selectMenuHandler
    timeout: 3
    environment:
      EVENT_BUS: micro-bots-event
    events:
      - http:
          method: post
          path: select-menu-handler

  shortMailCommand:
    handler: src/short-mail/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: short-mail-command
  shortMailEvent:
    handler: src/short-mail/event-handler.eventHandler
    timeout: 20
    maximumRetryAttempts: 0
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "ShortMailRequestedEvent"
  sickNoteCommand:
    handler: src/sick-note/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: sick-note-command
  sickNoteEvent:
    handler: src/sick-note/event-handler.eventHandler
    timeout: 20
    maximumRetryAttempts: 0
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "SickNoteRequestedEvent"

  slackInteraction:
    handler: src/slack/interaction-handler.interactionHandler
    timeout: 3
    environment:
      EVENT_BUS: micro-bots-event
    events:
      - http:
          method: post
          path: slack-interaction
  ##
  ## Unlock Project
  ##

  unlockProjectCommand:
    handler: src/unlock-project/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: unlock-project-command
  unlockProjectEvent:
    handler: src/unlock-project/event-handler.eventHandler
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "UnLockProjectRequestedEvent"

  vacationHandover:
    events:
      - schedule:
          enabled: true
          rate: cron(5 4 * * ? *) # at 4:05 AM (UTC) every day
    handler: src/functions/vacation-handover.handler
    memorySize: 128

  holidaySetAutomaticMailReplies:
    handler: src/functions/holiday-set-automatic-mail-replies.handler
    timeout: 3
    events:
      - schedule:
          enabled: false
          rate: cron(5 4 * * ? *) # at 4:05 AM (UTC) every day
    environment:
      HOLIDAY_MAIL_REPLIES_CHANGE_SLACK_CHANNEL: ${env:HOLIDAY_MAIL_REPLIES_CHANGE_SLACK_CHANNEL}
      MICROSOFT_TOKEN: ${env:MICROSOFT_TOKEN}
      MICROSOFT_CLIENT_ID: ${env:MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${env:MICROSOFT_CLIENT_SECRET}

  recruitmentIncomingMail:
    handler: src/recruitment/incoming-mail.handler
    memorySize: 256
    url: true
    tracing: Active
    environment:
      GITLAB_TOKEN: ${env:GITLAB_TOKEN_RECRUITMENT}
      MICROSOFT_TOKEN: ${env:MICROSOFT_TOKEN}
      MICROSOFT_CLIENT_ID: ${env:MICROSOFT_CLIENT_ID}
      MICROSOFT_CLIENT_SECRET: ${env:MICROSOFT_CLIENT_SECRET}
