service: birthday-bot

frameworkVersion: '1'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  profile: newcubator-dev

functions:
  bot:
    handler: handler.bot
    memorySize: 128
    environment:
      MOCO_TOKEN: ${env:MOCO_TOKEN}
      SLACK_TOKEN: ${env:SLACK_TOKEN}
      LEAD_TIME: 14
    events:
      - schedule:
          rate: cron(5 8 * * ? *)
          enabled: true
