service: micro-bots

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  stage: production
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: "arn:aws:ses:eu-central-1:931595285256:identity/newcubator.com"
        - Effect: "Allow"
          Action:
            - "events:PutEvents"
          Resource:
            - "*"
        - Effect: "Allow"
          Action:
            - "lambda:ListTags"
          Resource:
            - "*"
  # https://www.serverless.com/framework/docs/deprecations/#LAMBDA_HASHING_VERSION_V2
  lambdaHashingVersion: 20201221
  eventBridge:
    # https://www.serverless.com/framework/docs/deprecations/#AWS_EVENT_BRIDGE_CUSTOM_RESOURCE
    useCloudFormation: true
  environment:
    AWS_ACCESS_KEY_ID_GOOGLE: ${env:AWS_ACCESS_KEY_ID_GOOGLE}
    AWS_SECRET_ACCESS_KEY_GOOGLE: ${env:AWS_SECRET_ACCESS_KEY_GOOGLE}
    AWS_SECRET_NAME: ${env:AWS_SECRET_NAME}
    GITLAB_BOOK_PROJECT_ID: ${env:GITLAB_BOOK_PROJECT_ID}
    GITLAB_TOKEN: ${env:GITLAB_TOKEN}
    MOCO_TOKEN: ${env:MOCO_TOKEN}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    GENERAL_CHANNEL: ${env:GENERAL_CHANNEL}

plugins:
  - serverless-esbuild
  - serverless-sentry

custom:
  esbuild:
    bundle: true
    sourcemap: true
  sentry:
    dsn: ${env:SENTRY_DSN}

functions:
  birthday:
    environment:
      LEAD_TIME: 21
    events:
      - schedule:
          enabled: true
          rate: cron(5 4 * * ? *) # at 4:05 AM (UTC) every day
    handler: src/functions/birthday.handler
    memorySize: 128
    timeout: 10
  bookIssueReminder:
    environment:
      GITLAB_PROJECT_ID: ${env:GITLAB_BOOK_PROJECT_ID}
      SLACK_CHANNEL_ID: ${env:GENERAL_CHANNEL}
    events:
      - schedule:
          enabled: true
          rate: cron(5 4 * * ? *) # at 4:05 AM (UTC) every day
    handler: src/functions/gitlab-issue-reminder.handler
    memorySize: 128
    timeout: 20

  ##
  ## Completion Notice
  ##

  completionNoticeCommand:
    handler: src/completion-notice/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: completion-notice-command

  completionNoticeEvent:
    handler: src/completion-notice/event-handler.eventHandler
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "CompletionNoticeRequestedEvent"

  contactRequest:
    events:
      - http:
          cors: true
          method: post
          path: contactRequest
    handler: src/functions/contact-request.handler
    memorySize: 128
  eventApplication:
    events:
      - http:
          cors: true
          method: post
          path: eventApplication
    handler: src/functions/event-application.handler
    memorySize: 128

  ##
  ## Lock Project
  ##

  lockProjectCommand:
    handler: src/lock-project/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: lock-project-command

  lockProjectEvent:
    handler: src/lock-project/event-handler.eventHandler
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "LockProjectRequestedEvent"

  mailSignature:
    events:
      - http:
          method: post
          path: mailSignature
    handler: src/functions/mail-signature.handler
    memorySize: 128
  mailSignatureGenerator:
    events:
      - http:
          method: get
          path: mailSignatureGenerator
    handler: src/functions/mail-signature-generator.handler
    memorySize: 128
  privateChannel:
    events:
      - http:
          method: post
          path: privateChannel
    handler: src/functions/private-channel.handler
    memorySize: 128
  twitterBot:
    environment:
      TWITTER_ACCESS_SECRET: ${env:TWITTER_ACCESS_SECRET}
      TWITTER_ACCESS_TOKEN: ${env:TWITTER_ACCESS_TOKEN}
      TWITTER_APP_KEY: ${env:TWITTER_APP_KEY}
      TWITTER_APP_SECRET: ${env:TWITTER_APP_SECRET}
      TWITTER_BOT_SPREADSHEET_ID: ${env:TWITTER_BOT_SPREADSHEET_ID}
    events:
      - schedule:
          enabled: true
          rate: cron(0 16 * * ? *)
    handler: src/functions/twitter-bot.handler
    memorySize: 128

  slackInteraction:
    handler: src/slack/interaction-handler.interactionHandler
    timeout: 3
    environment:
      EVENT_BUS: micro-bots-event
    events:
      - http:
          method: post
          path: slack-interaction
  ##
  ## Unlock Project
  ##

  unlockProjectCommand:
    handler: src/unlock-project/command-handler.commandHandler
    timeout: 3
    events:
      - http:
          method: post
          path: unlock-project-command
  unlockProjectEvent:
    handler: src/unlock-project/event-handler.eventHandler
    events:
      - eventBridge:
          eventBus: micro-bots-event
          pattern:
            detail-type:
              - "UnLockProjectRequestedEvent"

  vacationHandover:
    events:
      - schedule:
          enabled: true
          rate: cron(5 4 * * ? *) # at 4:05 AM (UTC) every day
    handler: src/functions/vacation-handover.handler
    memorySize: 128
