service: micro-bots

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: production
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ses:SendEmail"
          Resource: "arn:aws:ses:eu-central-1:931595285256:identity/newcubator.com"
  environment:
    AWS_ACCESS_KEY_ID_GOOGLE: ${env:AWS_ACCESS_KEY_ID_GOOGLE}
    AWS_SECRET_ACCESS_KEY_GOOGLE: ${env:AWS_SECRET_ACCESS_KEY_GOOGLE}
    AWS_SECRET_NAME: ${env:AWS_SECRET_NAME}
    COMPLETION_NOTICE_CHANNEL: ${env:COMPLETION_NOTICE_CHANNEL}
    EMPLOYEE_NAMES: ${env:EMPLOYEE_NAMES}
    HANNOVER_CHANNEL_ID: ${env:HANNOVER_CHANNEL_ID}
    MOCO_TOKEN: ${env:MOCO_TOKEN}
    SLACK_TOKEN: ${env:SLACK_TOKEN}
    SPREADSHEET_ID: ${env:SPREADSHEET_ID}
    WORKLOAD_CHANNEL: ${env:WORKLOAD_CHANNEL}
    WORKLOAD_PERCENTAGE: ${env:WORKLOAD_PERCENTAGE}

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    sourcemap: true
    loader:
      .png: dataurl

functions:
  birthday:
    environment:
      LEAD_TIME: 21
    events:
      - schedule:
          enabled: true
          rate: cron(5 4 * * ? *)
    handler: src/functions/birthday.handler
    memorySize: 128
    timeout: 10
  completionNotice:
    events:
      - http:
          method: post
          path: completionNotice
    handler: src/functions/completion-notice.handler
    memorySize: 128
    timeout: 15
  contactRequest:
    events:
      - http:
          cors: true
          method: post
          path: contactRequest
    handler: src/functions/contact-request.handler
    memorySize: 128
  eventApplication:
    events:
      - http:
          cors: true
          method: post
          path: eventApplication
    handler: src/functions/event-application.handler
    memorySize: 128
  lockProject:
    events:
      - http:
          method: post
          path: lockProject
    handler: src/functions/lock-project.handler
    memorySize: 128
  mailSignature:
    events:
      - http:
          method: post
          path: mailSignature
    handler: src/functions/mail-signature.handler
    memorySize: 128
  mailSignatureGenerator:
    events:
      - http:
          method: get
          path: mailSignatureGenerator
    handler: src/functions/mail-signature-generator.handler
    memorySize: 128
  privateChannel:
    events:
      - http:
          method: post
          path: privateChannel
    handler: src/functions/private-channel.handler
    memorySize: 128
  unlockProject:
    events:
      - http:
          method: post
          path: unlockProject
    handler: src/functions/unlock-project.handler
    memorySize: 128
  workload:
    events:
      - http:
          method: post
          path: workload
    handler: src/functions/workload.handler
    memorySize: 128
  workloadAll:
    events:
      - http:
          method: post
          path: workloadAll
      - schedule:
          enabled: true
          rate: cron(0 16 ? * FRI *)
    handler: src/functions/workload-all.handler
    memorySize: 128
